Computing dependencies
Analyzing 90 sources with 0 local dependencies
ninja: Entering directory `output/facebookresearch__Detectron'
[1/90] check detectron.utils.__init__
[2/90] check detectron.__init__
[3/90] check detectron.modeling.__init__
[4/90] check detectron.datasets.__init__
[5/90] check detectron.roi_data.__init__
[6/90] check detectron.ops.__init__
[7/90] check detectron.core.__init__
[8/90] check detectron.datasets.coco_to_cityscapes_id
[9/90] check detectron.modeling.generate_anchors
[10/90] check detectron.modeling.name_compat
[11/90] check detectron.utils.timer
[12/90] check detectron.utils.collections
[13/90] check detectron.utils.image
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/image.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/imports/detectron.utils.image.imports --module-name detectron.utils.image -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/image.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/image.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/image.py", line 23, in <module>: Can't find module 'cv2'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[14/90] check detectron.datasets.dataset_catalog
[15/90] check setup
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/setup.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/imports/setup.imports --module-name setup -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/setup.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/setup.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/setup.py", line 20, in <module>: Can't find module 'Cython.Build'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[16/90] check detectron.utils.colormap
[17/90] check detectron.utils.env
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/env.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/imports/detectron.utils.env.imports --module-name detectron.utils.env -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/env.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/env.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/env.py", line 45, in set_up_matplotlib: Can't find module 'matplotlib'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[18/90] check detectron.utils.segms
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/segms.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/imports/detectron.utils.segms.imports --module-name detectron.utils.segms -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/segms.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/segms.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/segms.py", line 32, in <module>: Can't find module 'pycocotools'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[19/90] check detectron.utils.model_convert_utils
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/model_convert_utils.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/imports/detectron.utils.model_convert_utils.imports --module-name detectron.utils.model_convert_utils -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/facebookresearch__Detectron/pyi/detectron/utils/model_convert_utils.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/model_convert_utils.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/model_convert_utils.py", line 27, in <module>: Can't find module 'caffe2.python'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/model_convert_utils.py", line 28, in <module>: Can't find module 'caffe2.proto'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/model_convert_utils.py", line 377, in compare_model: No attribute 'shape' on None [attribute-error]
  In Optional[Any]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/model_convert_utils.py", line 379, in compare_model: No attribute 'shape' on None [attribute-error]
  In Optional[Any]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/facebookresearch__Detectron/detectron/utils/model_convert_utils.py", line 391, in save_graph: Can't find module 'caffe2.python'. [import-error]

For more details, see https://google.github.io/pytype/errors.html
[20/90] check detectron.utils.logging
[21/90] check detectron.datasets.dummy_datasets
[22/90] check detectron.utils.coordinator
[23/90] check detectron.utils.io
ninja: build stopped: subcommand failed.
Leaving directory 'output/facebookresearch__Detectron'
